version: 2.1

jobs:
  build_and_test:
    machine: true # This enables the machine executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
      - run:
          name: Install NPM packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  test_my_app:
    jobs:
      - build_and_test
