version: 2.1

jobs:
  build_and_test:
    machine: true 
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - run:
          name: Install Python dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run tests with pytest
          command: pytest

workflows:
  test_my_app:
    jobs:
      - build_and_test
